version: "3.8"
services:
  calculator-api:
    build:
      context: ./Calculator.WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    links:
      - "addition-api"
      - "subtraction-api"
    depends_on:
      - addition-api
      - subtraction-api
  addition-api:
    build:
      context: ./Calculator.Add.WebApi
      dockerfile: Dockerfile
    ports:
      - "5001:80"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  subtraction-api:
    build:
      context: ./Calculator.Sub.WebApi
      dockerfile: Dockerfile
    ports:
      - "5002:80"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80